### ISSUE TITLE
problem with mint

### ISSUE THREAD

**Issue by thierryH91200** [SvenTiigi/SwiftKit#1]
> ℹ Please fill out this template when filing an issue.

> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.

## SwiftKit Environment

**SwiftKit version:**
**macOS version:10.14
**Package manager:**
- [ ] Brew
- [x ] Mint

## What did you do?

ℹ install with mint

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.

## What happened instead?

 ```
 mint install SvenTiigi/SwiftKit
🌱  Finding latest version of SwiftKit
🌱  Cloning SwiftKit 1.0.0
🌱  Resolving package
dyld: Library not loaded: @rpath/llbuild.framework/Versions/A/llbuild
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/swift-package
  Reason: image not found
🌱  Encountered error during "swift package resolve". Use --verbose to see full output
🌱  **Failed to resolve SwiftKit 1.0.0 with SPM**
iMac-de-thierry:SwiftKit-master thierryh24$ 
```

I do not know what to do ???

**Comment by SvenTiigi** [comment]
Hey @thierryH91200,

It seems like your Xcode Command Line Tools aren't configured to the latest one (https://stackoverflow.com/questions/55432373/unable-to-run-swift-package-manager-macos-10-14-4).

I've downgraded the `swift-tools-version` on the `Package.swift` to `4.0` please check if this helps by re-installing with mint and using the master branch.

```bash
mint install SvenTiigi/SwiftKit@master --force
```

If this not helps please install the latest Xcode Command Line Tools.

**Comment by thierryH91200** [comment]
hey @SvenTiigi 

with

`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

it's fine


```
mint install SvenTiigi/SwiftKit
🌱  Finding latest version of SwiftKit
🌱  Cloning SwiftKit 1.0.0
🌱  Resolving package
🌱  Building package
🌱  Installed SwiftKit 1.0.0
🌱  Linked swiftkit 1.0.0 to /usr/local/bin
```

Thanks
