### ISSUE TITLE
Integration with Periphery

### ISSUE THREAD

**Issue by arguiot** [SvenTiigi/SwiftKit#2]
There should be an option to add https://peripheryapp.com to the project. So unused is automatically flagged.

**Comment by SvenTiigi** [comment]
Hey @arguiot,

Thanks for your feature request.

Please feel free to open a PR to get started.

Maybe something like [`xcodeproj`](https://github.com/tuist/xcodeproj) is needed in order to remove the Periphery target from the Xcode project if Periphery shouldn't be integrated.

**Comment by SvenTiigi** [comment]
Closing due inactivity. Feel free to re-open the issue at any time.
