### ISSUE TITLE
No option for custom template

### ISSUE THREAD

**Issue by wildthink** [SvenTiigi/SwiftKit#4]
## SwiftKit Environment

It would be great if I could provide and select from multiple templates.

**Comment by SvenTiigi** [comment]
Hey @wildthink 

Thanks for opening an issue.

To get you right you want to pass in a different Repository URL to clone the Template Project from?

**Comment by wildthink** [comment]
I think that would do the trick. I was thinking that one might want to offer different configurations and/or pre-populate with some starter code or such.
Thanks.

**Comment by SvenTiigi** [comment]
Hey @wildthink 

Please check out the latest Release [`1.2.5`](https://github.com/SvenTiigi/SwiftKit/releases/tag/1.2.5) which now includes the `--repository` parameter to specify the location where to clone the `SwiftKit` repository from.

| Long parameter | Short parameter | Description
| ----------- | ----------- | -------------- |
| `--repository` | `-r` | The SwiftKit template repository url 🌎 |

```bash
$ swiftkit new MyAwesomeKit --repository https://github.com/Custom/MyCustomSwiftKit.git
```
