### ISSUE TITLE
Feature Request: Support for GitHub Repo Templates

### ISSUE THREAD

**Issue by codytwinton** [SvenTiigi/SwiftKit#5]
Support for [GitHub Repo Templates](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) would be awesome!

**Comment by SvenTiigi** [comment]
Hey @codytwinton 

This looks awesome. Will look forward to add this soon 🙌

**Comment by SvenTiigi** [comment]
Hi @codytwinton

I took a closer look to GitHub Repo Templates and sadly there is no option to perform any kind of customization which is needed to correctly configure the Xcode Template Project based on various variables like Project name, Bundle Identifier, Targets, CI-Service, etc... .
