### ISSUE TITLE
Failed to build SwiftKit 1.3.2 with SPM

### ISSUE THREAD

**Issue by alexanderpuchta** [SvenTiigi/SwiftKit#6]
## SwiftKit Environment

- SwiftKit version: 1.3.2
- macOS version: 10.15.7
- Xcode version: 12.1
- Installed via (mint, brew): brew + mint

## What did you do?

> brew tap SvenTiigi/SwitfKit
> brew install swiftkit

## What did you expect to happen?

> successful installation of SwiftKit 

## What happened instead?

> ==> Installing swiftkit from sventiigi/swiftkit
> ==> Downloading https://github.com/SvenTiigi/SwiftKit/archive/1.3.2.tar.gz
> ==> Downloading from https://codeload.github.com/SvenTiigi/SwiftKit/tar.gz/1.3.2
> #=#=#                                                                         
> ==> swift build --disable-sandbox -c release

'XcodeProj' /private/tmp/swiftkit-20201104-23612-a6gsum/SwiftKit-1.3.2/.build/checkouts/xcodeproj: error: Source files for target XcodeProj should be located under 'Sources/XcodeProj', or a custom sources path can be set with the 'path' property in Package.swift

==> Formula
Tap: sventiigi/swiftkit
Path: /usr/local/Homebrew/Library/Taps/sventiigi/homebrew-swiftkit/swiftkit.rb
==> Configuration
HOMEBREW_VERSION: 2.5.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c822206a05cd7fffe526b8e0fa2f45365be72a5
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f8c50a382156306b36d413eb5f8f98d464ebc9e9
Core tap last commit: 69 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15
macOS: 10.15.7-x86_64
CLT: 12.1.0.0.1.1602137645
Xcode: 12.1
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin

Error: sventiigi/swiftkit/swiftkit 1.3.2 did not build

**Comment by SvenTiigi** [comment]
Hey @alexanderpuchta 

Thanks for your detailed bug report.

It seems like the dependency [XcodeProj](https://github.com/tuist/xcodeproj) which is used by SwiftKit fails to build due to an updated requirement of SPM that the name of a Swift Package must match the directory name inside the `Sources` directory.

I have updated the dependency on the [develop](https://github.com/SvenTiigi/SwiftKit/tree/develop) branch.

Please let me know if this resolve your issue:
```
mint install SvenTiigi/SwiftKit@develop
```

**Comment by alexanderpuchta** [comment]
Hey, thank you! I was able to install the SwiftKit!

**Comment by SvenTiigi** [comment]
Perfect 👍 

The bug fix is now available with the new version [1.3.3](https://github.com/SvenTiigi/SwiftKit/releases/tag/1.3.3) of SwiftKit
